### Get quizzes
GET http://localhost:3000/quiz



### Add new quiz
POST http://localhost:3000/quiz
Content-Type: application/json

{
  "title": "123",
  "description": "123456"
}

### Get quiz by id
GET http://localhost:3000/quiz/1

### Delete quiz

DELETE http://localhost:3000/quiz/3

### Update quiz

PUT http://localhost:3000/quiz/1
Content-Type: application/json

{
  "title": "Validation OK",
  "description": "PUT sorulari"
}

### Update using PATCH method

PATCH http://localhost:3000/quiz/1
Content-Type: application/json

{
  "description": "PATCH ile güncellendi"
} 

### Get users

GET http://localhost:3000/user

### Get user by id

GET http://localhost:3000/user/1/

### Register

POST http://127.0.0.1:3000/user/register/
Content-Type: application/json

{
  "username": "nestjs",
  "email": "nestjs@gmail.com",
  "password": "nestjs"
}